test/ome-files/formatreader.cpp
test/ome-files/metadatatools.cpp

Matches OME-XML sample renaming in https://github.com/openmicroscopy/bioformats/pull/2288

Fix name of OME-XML samples used in formatreader and metadatatools tests

---

lib/ome/files/PixelProperties.cpp
lib/ome/files/VariantPixelBuffer.h
lib/ome/qtwidgets/TexelProperties.cpp

Use Boost.Preprocessor to remove large sets of hardcoded switch case statements.  This will make the code easier to adapt to model changes, as well as simplifiying it.
See also: https://github.com/openmicroscopy/bioformats/pull/2303
--------
Testing: The builds will fail horribly if this doesn't work, so checking they are green should be sufficient.  If you want to, you can check that the preprocessed source code looks nice.  See the other PR for the instructions.

Use enum value list macros to simplify switch statements

---

scripts/source-archive

Correct newline stripping.  To test:
```
scripts/source-archive --release=test --target=/tmp --tag=HEAD
```
Check `cmake/GitVersion.cmake` in the tar archive.  The shortversion will now not have a trailing newline.

source-archive: Strip newline for git shortrevision

---

scripts/source-archive

Correct  timestamp
```
scripts/source-archive --release=test --target=/tmp --tag=HEAD
```
Check `cmake/GitVersion.cmake` in the tar archive.  The version will also be the current date and time, rather than 1-1-1970.

source-archive: Set GitVersion mtime

---

CMakeLists.txt

Due to the find_package macro setting the version numbers using the same variable names we set ourselves, this was overwriting the correct version number for this component with one from ome-common.  This patch fixes that, and also ensures that the generated configuration file is using LF line endings, so we can source it in a shell on Windows without getting CRs in the variables.
--------
See https://github.com/ome/ome-cmake-superbuild/pull/52 for testing instructions.

cmake: Correct config script version and line endings

---

lib/ome/files/tiff/IFD.cpp
test/ome-files/data/CMakeLists.txt
test/ome-files/tiff.cpp

- Add tests for non-square images.  Previously tested only with 64x64 images; it now tests with a variety of POT and N-POT sizes (32, 43, 64) × (32, 37, 64) to ensure correctness
- Reference PNG images of different sizes are generated with graphicsmagick `convert` as for the TIFF read tests
- The test count is kept reasonable by selecting a random subset of 4000 or 200 tests out of a full set of ~40000.
- The special case behaviour of the BIT pixel type is adjusted to pad to the next byte at the end of scanlines, rather than padding at the end of the strip or tile.  This matches the behaviour of libtiff for strips, and also the MacOSX TIFF implementation (at least for planar data; it fails to work with chunky data, but likely a bug in the MacOS TIFF library or viewer given the rarity of …

Non-square TIFF tests

---

docs/sphinx/conf.py.in

Fix the naming of command manual pages; this is a regression as a result of the renaming.
Testing: the `ome-files --help` and `ome-files info --help` commands should display a manual page.

docs: Correct names of command manpages

---

cmake/GTest.cmake

See https://github.com/ome/ome-cmake-superbuild/pull/64

cmake: Remove VC11 faux variadic templates workaround

---

docs/sphinx/overview.txt

Corrects the package names in the installation instructions. Compare with https://packages.debian.org/stable/libdevel/.

remove extraneous hyphens from Debian package names

---

docs/sphinx/examples/pixeldata.cpp
lib/ome/files/PixelProperties.cpp
lib/ome/files/PixelProperties.h
lib/ome/files/VariantPixelBuffer.h
lib/ome/files/tiff/IFD.cpp
test/ome-files/formatreader.cpp
test/ome-files/formatwriter.cpp
test/ome-files/pixel.h
test/ome-files/pixelbuffer-complex.cpp
test/ome-files/pixelbuffer-doublecomplex.cpp
test/ome-files/pixelproperties.cpp
test/ome-files/variantpixelbuffer.cpp

This is limited to the following enum changes:
- COMPLEX to COMPLEXFLOAT
- DOUBLECOMPLEX to COMPLEXDOUBLE

Upgrade to use the 2016-DEV0 API

---

cmake/TemplateShellWrapper.cmake.in

https://trello.com/c/5HAmHU45/25-man-use-absolute-paths
This corrects the `ome-files` command wrapper to compute the installation prefix using a portable `realpath`, and then drop the bin path from it.  The previous approach worked but wasn't strictly portable and contained a non-canonical path containing relative parts which broke the "man" command on MacOS X.
--------
Testing: `ome-files --help` will now work on MacOS X.  Download the build from https://ci.openmicroscopy.org/view/Files-DEV/job/OME-FILES-CPP-DEV-merge-superbuild/BUILD_TYPE=Release,node=koi/lastSuccessfulBuild/artifact/artefacts/binaries/ and run `ome-files --help`.  It will now work.  The other `ome-files` options and commands like `info` will continue to work.

ome-files: Wrapper script computes absolute path portably

---

lib/ome/files/MetadataTools.cpp
lib/ome/files/in/OMETIFFReader.cpp
lib/ome/files/in/OMETIFFReader.h

Correct metadata validation errors in OMETIFFReader:
- Don't add BinData elements by setting the BigEndian property; set BigEndian on Pixels instead
- Move the BigEndian setting to `initFile` alongside all the other metadata setting
- Remove the unnecessary metadata functions
- Don't set MetadataOnly when TiffData elements are present, copying the Java logic.
Testing:
Run `ome-files info --omexml` on one of the problematic OME-TIFF files.  With this PR, the errors should no longer occur.

OMETIFFReader: Do not add BinData elements to Pixels

---

lib/ome/files/in/OMETIFFReader.cpp
lib/ome/files/in/OMETIFFReader.h

With these changes, all 2016-06 sample data can be read successfully:
```
(for pat in "*.tif" "*.tiff" "*.tf2" "*.tf8" "*.btf" "*.companion.ome"; do find ~/images/ome-tiff/ome-schemas/2016-06 -name "$pat"; done) | while read f; do echo "TEST READ: $f"; ome-files info "$f" || echo "**FAIL**: $f" ; done
```
This will test opening of every file in every fileset.

OMETIFFReader: Assorted multi-file fixes

---

cmake/TemplateShellWrapper.cmake.in

This copies the logic used by the bioformats java command wrappers, to permit use via a symlink.  This is needed to allow homebrew to correctly symlink `bin/ome-files` and then have it pick up all the correct paths.
Testing: Unpack a build, symlink `bin/ome-files` from somewhere else e.g. `/tmp/test`, and invoke `info` and `--usage` via the link.

ome-files: Support invocation via a symlink

---

lib/ome/files/tiff/Field.cpp
lib/ome/files/tiff/IFD.cpp
lib/ome/files/tiff/IFD.h

The most important is the last commit to correct the handling of the `COLORMAP` tag.  This allows the OME-TIFF reader to read and display a file with a Windows Debug build without throwing a runtime error.  It was triggering a stack guard, and was also buggy (but silently working but incorrectly) on all other platforms.
Testing: Download Windows VS2015 64-bit debug build.  Run `bin\ome-files info \path\to\tiff` where the TIFF is an OME-TIFF with colourmap.  (bfconvert a CZI/LSM to OME-TIFF to get one if you don't have one.)  If you compare with the 0.2.1 release download, this this will run without problems while the release download will display an exception dialogue when the stack guard is tripped.

TIFF wrapper fixes

---

lib/ome/files/in/OMETIFFReader.cpp

Don't make any assumptions regarding the ordering or presence of plane elements.
This is a conversion of https://github.com/openmicroscopy/bioformats/pull/2615/files for C++.
Testing: With a suitably broken OME-TIFF, you should see some warnings about setting unset plane parameters to zero.
This is the final (only) change for the 0.2.3 release.

OMETIFFReader: Handle missing plane parameters

---

lib/ome/files/FormatWriter.h
lib/ome/files/detail/FormatWriter.cpp
lib/ome/files/detail/FormatWriter.h
lib/ome/files/out/MinimalTIFFWriter.cpp
lib/ome/files/out/OMETIFFWriter.cpp
lib/ome/files/tiff/Codec.cpp
lib/ome/files/tiff/Codec.h
lib/ome/files/tiff/IFD.cpp
lib/ome/files/tiff/IFD.h
lib/ome/files/tiff/Types.h
test/ome-files/formatwriter.cpp
test/ome-files/minimaltiffwriter.cpp
test/ome-files/ometiffwriter.cpp
test/ome-files/tiff.cpp
test/ome-files/tiffsamples.cpp
test/ome-files/tiffsamples.h

- Allow introspection of TIFF codec support on a per-pixeltype basis; add `getCodecNames` and `getCodecScheme` to the tiff Codec support functions
- Allow the writer interface to query valid codecs for a given pixel type by adding `getCompressionTypes(PixelType)` which is a rather more useful variant than the existing `getPixelTypes(codec)` (which might be deprecated and removed).  In the common case, you might want to select a compression type for a given set of pixel data, but altering the pixel data to use a different type to support a certain codec is less common
- Add the supported codecs to the TIFF writers, so that they can be queried and set with the `FormatWriter` interface
- Add unit tests to test with LZW and Deflate compression for the core libtiff wrappers and the Minimal …

Add support for TIFF compression

---

lib/ome/files/detail/FormatReader.cpp

With this PR, if `getRGBChannelCount` is called before `setId`, the error message is `"Current file should not be null; call setId() first"`, consistently with other similar methods. Without this PR, the error message is `"vector"`.

Call assertId in getRGBChannelCount

---

lib/ome/files/FormatReader.h
lib/ome/files/MetadataTools.h
test/ome-files/formatwriter.cpp

Trivial fix to explicitly include a header currently included indirectly via the model headers.  This will break the build when the `basic-c++11` branch for ome-model is merged, since the needed header will then no longer be included.  It will be later removed by the `basic-c++11` branch for this component; the change here is to allow for a smooth transition to ensure compatibility for end users, by verifying that the compatibility headers work across the board during and after this transition.
Testing: Check builds are green.

Add missing indirect includes

---

docs/sphinx/conf.py.in

Ports same policy from `ome-model`. Docs CI should be green.
Also see https://github.com/ome/ome-cmake-superbuild/pull/114.

set docs linkcheck timeout to 30s

---

lib/ome/files/FormatReader.h
lib/ome/files/FormatWriter.h

Part of https://github.com/ome/ome-model/pull/25.  Needed to avoid compile failures due to using indirect includes of compatibility headers.

Add missing ome/compat/memory.h includes

---

lib/ome/files/in/OMETIFFReader.cpp
lib/ome/files/in/OMETIFFReader.h
lib/ome/files/tiff/IFD.h
lib/ome/files/tiff/TIFF.cpp

- The OME-TIFF reader was supposed to be caching open TIFF reader instances, but in practice it was not doing the caching properly, and was repeatedly re-opening the same TIFF file instead of using the cached one; it now opens each TIFF once only and correctly retrieves it from the cache
- The TIFF libtiff wrapper class was not caching IFD offsets, leading to repeated linear scans through the IFDs when accessing by index; now we cache all IFDs up front which means a single linear scan on open and then constant-time access
The first was the most painful, giving a 6× improvement with BBBC/mitocheck data (120s → 20s).  The second was less impressive at 1.1× (20s → 18s) but still useful.
The TIFF caching does need to also think about closing TIFFs (we currently leave them open indefinitely). …

TIFF read performance improvements

---

lib/ome/files/in/OMETIFFReader.cpp
lib/ome/files/out/OMETIFFWriter.cpp

Set the interleaved property correctly for the OME-TIFF reader (the other readers use the coremetadata conversion from till/Util.cpp which already has this behaviour).
Testing: Check builds are green.  There's no change to openbytes since the pixel buffer was already in the correct order; this simply corrects the isInterleaved property to match reality rather than fixing it to false.

OMETIFFReader: Set interleaving according to IFD PlanarConfiguration

---

lib/ome/files/out/OMETIFFWriter.cpp
test/ome-files/ometiffwriter.cpp

Enable TIFF compression when setting up each IFD.  This duplicates the existing support in MinimalTIFFWriter.  Tested in the unit test.
Testing: Check builds are green.  Run `tiffinfo` on one of the files under `ome-files-build/test/ome-files/data/ometiffwriter-*` and check that the compression scheme was set to deflate.  You should see:
```
Compression Scheme: Deflate
```

OMETIFFWriter: Enable compression support

---

lib/ome/files/out/MinimalTIFFWriter.cpp
lib/ome/files/out/OMETIFFWriter.cpp

Make the C++ TIFF writers faster by using some simple heuristics to set the default strip and tile sizes.  Note: they are based solely upon the image dimensions and do not take pixel size or sample count into account.  We can do more sophisticated profiling later on and adjust the heuristics accordingly.  Also, once we have a proper tile/chunk-based replacement for saveBytes, we can make a number of assumptions and performance optimisations when the buffer size is of an expected and enforced size.
The current default: STRIP with a stripsize of 1.
For a 512×512 image, this means 512 strips of 1 row and when writing a whole plane, this means inserting 512 separate entries into the tile cache before flushing them out.  This is inefficient due to allocating 512 buffers and inserting them into …

Improve TIFF write performance

---

lib/ome/files/MetadataTools.cpp

The existing uses of resolveReferences using the MetadataStore method of the same name has no effect.  This is because the OMEModel owned by the OMEXMLMetadataStore is never used for anything, because the helper methods are here in ome-files/formats-api on MetadataTools/OMEXMLService instead of the model.  Same problem for Java.  Ideally we'll move them over to where they belong.
This enables deserialisation of references.  Serialisation is still broken; later stages of deserialisation may also still need further work.
Testing: Check builds are green.  See https://github.com/ome/ome-model/pull/30/files

MetadataTools: Resolve references after updating model objects

---

cmake/TemplateCmdWrapper.cmake.in
cmake/TemplateShellWrapper.cmake.in

See https://trello.com/c/4mdYwpIP/6-update-end-copyright-year
To test this PR check
```
ome-files --version
ome-files info --version
```
In both cases, the copyright should include 2017 in the year range

Fix copyright year range for main ome-files --version

---

CMakeLists.txt

In preparation of the upcoming release.
Also bump the ome-model component version to 5.5.1 as coupled changes were brought in to fix metadata parsing issues.

Bump ome-files-cpp release version to 0.3.1

---

lib/ome/files/out/MinimalTIFFWriter.cpp

Same fix as for https://github.com/ome/ome-files-cpp/pull/49 for ome-tiff
Testing: Check builds are green.

MinimalTIFFWriter: Interleaving behaviour is the same as OME-TIFF

---

lib/ome/files/FormatTools.cpp
test/ome-files/formatreader.cpp

Changes `getZCTCoords` to throw when the given index is too big.

getZCTCoords: check index vs max value

---

docs/sphinx/examples/metadata-formatwriter.cpp
lib/ome/files/FormatWriter.h
lib/ome/files/detail/FormatWriter.cpp
lib/ome/files/detail/FormatWriter.h
lib/ome/files/out/MinimalTIFFWriter.cpp
lib/ome/files/out/MinimalTIFFWriter.h
lib/ome/files/out/OMETIFFWriter.cpp
lib/ome/files/out/OMETIFFWriter.h
test/ome-files/data/CMakeLists.txt
test/ome-files/minimaltiffwriter.cpp
test/ome-files/ometiffwriter.cpp
test/ome-files/tiff.cpp
test/ome-files/tiffsamples.cpp
test/ome-files/tiffsamples.h

https://trello.com/c/y1HuXrzQ/17-formatwriter-bio-formats-tiling-api-backport
A little different than the Java API in these respects:
- getters and setters pass `optional<size>` rather than `size`.  This was already used by other settable properties here, and it allows us to detect the "unset by user" case.  This is important to distinguish between strips and tiles at the limits where the tile/strip x size == the image x size
- we don't pass back the set value in the `set` methods as a result
- `getEffectiveTileSize[XY]` allows querying of the reader-specific tile size set in response to the size request.  This can modify the user's intent with reader-specific constraints.
- `MinimalTIFFWriter` and `OMETIFFWriter` updated to implement `getEffectiveTileSize[XY]`; they report back the sizes …

Add Tiling API for writers

---

lib/ome/files/PixelBuffer.h
lib/ome/files/VariantPixelBuffer.cpp
lib/ome/files/VariantPixelBuffer.h

See [trac ticket](https://svn.boost.org/trac/boost/ticket/11251).  This is a workaround for a bug in Boost 1.58, as provided by Ubuntu 16.04.
Testing: should build fine on the existing CI nodes.  This will make the build also work on Ubuntu 16.04; should go green (well, blue) on the test Ubuntu 16.04 CI node.
Getting this into the next milestone would be useful.  Firstly for the benefit of users on the current Ubuntu LTS release, and secondly to allow testing and subsequent deployment of the new CI infrastructure.
Testing: check job status.  There are no functional changes.

PixelBuffers: Don't use static_vistors returning references

---

lib/ome/files/FormatHandler.h
lib/ome/files/FormatReader.h
lib/ome/files/FormatWriter.h
lib/ome/files/PixelBuffer.h
lib/ome/files/TileBuffer.h
lib/ome/files/TileCache.h
lib/ome/files/VariantPixelBuffer.h
lib/ome/files/detail/FormatReader.h
lib/ome/files/detail/FormatWriter.h
lib/ome/files/in/MinimalTIFFReader.h
lib/ome/files/out/MinimalTIFFWriter.h
lib/ome/files/tiff/Field.h
lib/ome/files/tiff/IFD.cpp
lib/ome/files/tiff/IFD.h
lib/ome/files/tiff/TIFF.cpp
lib/ome/files/tiff/TIFF.h
lib/ome/files/tiff/TileInfo.h

Upgrade to the latest Doxygen configuration file version.
Doxygen can't handle deleted methods too well--it complains about
them not being documented despite them not existing at all, so
skip them entirely.
Testing: Check builds are green.

Update API reference including use of deleted methods

---

docs/sphinx/examples/metadata-formatwriter.cpp
docs/sphinx/examples/metadata-formatwriter2.cpp
docs/sphinx/tutorial.rst

See [trello card](https://trello.com/c/oEwb3o57/34-add-writer-examples)
Testing:
- check builds are green
- check tutorial page in docs, see [staging docs](http://www.openmicroscopy.org/site/support/ome-files-cpp-staging/ome-files/manual/html/tutorial.html)
- check emitted model is valid (it validates, but is it semantically valid with regard to annotation names, references)?
metadata-formatwriter:
```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?><OME xmlns="http://www.openmicroscopy.org/Schemas/OME/2016-06" UUID="urn:uuid:d5426311-a8b1-45f3-835d-7a6c703bc50a" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2016-06 http://www.openmicroscopy.org/Schemas/OME/2016-06/ome.xsd"><Instrument ID="Instrument:0"><Detector …
```

docs: Add extended metadata examples including annotations and references

---

cmake/TemplateCmdWrapper.cmake.in
cmake/TemplateShellWrapper.cmake.in
docs/sphinx/commands/ome-files.rst

- Remove last two remaining instances of `ome-files-test`; now called `ome-files`
- Document that `ome-files view` may not work if support was not compiled in

ome-files: Wrapper documentation fixes

---

CMakeLists.txt
cmake/FindBoost.cmake
lib/ome/files/tiff/Field.cpp

See https://github.com/ome/ome-cmake-superbuild/pull/159 for testing instructions.
The tiff change was to explicitly include headers which were previous included indirectly via a Boost header, but the implicit include no longer happens with Boost 1.65.

Boost 1.65

---

lib/ome/files/OMEFilesConfig.cmake.in

This is added implicitly by find_dependency.
See https://github.com/ome/ome-common-cpp/pull/51 for context.

cmake: Remove REQUIRED from exported configuration

---

docs/sphinx/conf.py.in

Re: https://github.com/openmicroscopy/sphinx-ignore-links/issues/1
This removes use of the external sphinc-ignore-links repo in favour of adding links here in future.

Remove sphinx-ignore-links repo in conf.py.in

---

CONTRIBUTING.md
README.md

See https://trello.com/c/oxWdJSKf/610-clean-up-remaining-links-to-site-support-old-docs-urls

Update docs links to use new URLs

---

CMakeLists.txt

Following the release of [OME Files 0.5.0](http://www.openmicroscopy.org/2017/12/04/ome-files-0-5-0.html), this PR increments the patch number
See also https://github.com/openmicroscopy/ome-documentation/pull/1819

Bump version to 0.5.1

---

lib/ome/files/CMakeLists.txt
lib/ome/files/out/OMETIFFWriter.cpp

Reorder of headers, similar to steps already taken in the past in other source files, e.g. `test/ome-files/metadatamap.cpp` but the other way around (at the beginning rather than the end, so the limits aren't yet set).
Testing: Check builds are green, the Windows builds in particular since VS2015 was the compiler previously failing without this tweak.

Boost 1.67 fixes
